services: 

  nginx:
    build:
      context: nginx
    container_name: nginx
    links:
      - app
    networks:
      - node-network
    ports:
      - "8080:80"
    depends_on:
      - app

  app:  
    build: 
      context: node
    command:  npm start
    container_name: app
    entrypoint: dockerize -wait tcp://db:3306 -timeout 20s docker-entrypoint.sh
    networks: 
      - node-network 
    tty: true    
    volumes:
      - ./node/app:/usr/src/app
    ports: 
      - "3000:3000"
    depends_on: 
       - db

  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes: 
      - ./mysql:/var/lib/mysql
    environment: 
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks: 
      - node-network    

networks: 
  node-network:
    driver: bridge 